# Evaluation configuration
model_path: "models/best_model.pth"
data_dir: "data/split"
output_dir: "results"
image_size: 384
batch_size: 16
num_workers: 4
save_heatmaps: true
heatmap_dir: "results/heatmaps"
predictions_csv: "results/predictions.csv"