data_dir: "data/split"
batch_size: 32
image_size: 384
num_workers: 0
epochs: 20
learning_rate: 0.001
weight_decay: 0.0001
min_lr: 0.000001
label_smoothing: 0.1
use_amp: true
grad_clip: 1.0
early_stop_patience: 5
model_dir: "models"
log_dir: "logs"
